---
- name: Generate wireguard config file
  ansible.builtin.template:
    src: conf.jinja2
    dest: /etc/wireguard/{{ wireguard_interface.name }}.conf

- name: start wireguard and enable on boot
  ansible.builtin.systemd:
    name: wg-quick@{{ wireguard_interface.name }}
    enabled: yes
    state: restarted